# Basic project details.
site_name: 'Phoenix Documentation'
site_description: 'Decentralized Protocol Clusters'
site_author: 'Phoenix Team'
site_url: ''

# Links to the core 'Phoenix smart contract repository.
repo_name: 'Phoenix'
repo_url: 'https://github.com/Phoenix-Finance'

# Setting `edit_uri` to an empty string disables the edit button, which points to the wrong page.
# If at some point this documentation is moved into the core  repository, then this can be
# removed.
edit_uri: ''

docs_dir: 'content'


# Top level headings become tabs at the top due to `tabs: true` in the theme.
nav:
  - Introduction: index.md
  - Phoenix Papers: 
    - Product Paper: about/productpaper.md
  - Products: 
    - Phoenix Protocol for Options (PPO): 
      - Introduction: products/options.md
      - Options Basics:  options/optionbasics.md
      - Options Key Terms:  options/terms.md
      - Options Strategies: options/strategies.md
      - PPO v1.0:  options/v1.0.md
      - Returns in the pool: options/financials.md
      - Risks in PPO v1.0: options/risks.md
      - Making PPO v1.0 Secure: options/security.md
    - Phoenix Protocol for Leveraged Tokens (PPLT):
      - Introduction: leveragedtokens/introduction.md
      - Leveraged Token Basics: leveragedtokens/basics.md
      - Comparison: leveragedtokens/comparison.md
      - PPLT v1.0:
        - Introduction: leveragedtokens/PPLT1.0/intro.md
        - How does FPLT v1.0 work: leveragedtokens/PPLT1.0/howtowork.md
        - Lending Pools: leveragedtokens/PPLT1.0/lendingpool.md
        - Rebalancing Mechanism: leveragedtokens/PPLT1.0/rebalance.md
      - Risks: leveragedtokens/risks.md
  - Phoenix Token (PHX): 
    - Addresses: token/address.md
  - Governance: 
    - Overview: governance/index.md
  - Terminology:
    - Overview:  terminology/index.md
    - DeFi Terms: terminology/defi.md
    - Options Terms: terminology/options.md
    - PPO Terms:  terminology/ppo.md
  - In-depth Reading: 
    - English: indepthreading/english.md
    - Chinese: indepthreading/chinese.md

  

 
# These social links will be rendered as icons in the footer, as long as the type corresponds to FontAwesome glyph.
extra:
  extra_javascript:
    - js/image_zoom.js
  social:
    - icon: 'brands/github'
      link: 'https://github.com/FinNexus'
    - icon: 'brands/twitter'
      link: 'https://twitter.com/fin_nexus'
    - icon: 'brands/reddit'
      link: 'https://www.reddit.com/r/finnexus/'
    - icon: 'brands/medium'
      link: 'https://medium.com/finnexus/'
    - icon: 'brands/discord'
      link: 'https://discord.gg/bCDMHN7'

# This set of documentation uses the MkDocs Material theme by squidfunk: https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'deep purple'
  logo: 'VI/logo256x256.png'
  favicon: 'img/favicon.ico'
  feature:
    tabs: false
    instant: false
    sections: true
    expand: true
    
    


plugins:
    - search
    

# Extension settings.
# In addition to the standard extensions, this also requires the PyMdown Extensions by facelessuser: https://github.com/facelessuser/pymdown-extensions
markdown_extensions:
  - toc:
      permalink: True # Generates permanent links for each page section.
      toc_depth: 10
  - admonition # Small descriptive elements for notes, warnings, etc.
  - pymdownx.arithmatex # Math rendering.
  - pymdownx.tasklist: # Allows nested and better checkboxes.
      custom_checkbox: True # Without this setting, checkboxes look rubbish in the material theme.
  - pymdownx.highlight: # Code syntax highlighting.
      linenums: True
  - pymdownx.extra: # Better fenced code blocks, emphasis, footnotes, lists, tables, abbreviations, and raw HTML.
      pymdownx.betterem:
        smart_enable: 'all' # Smarter line breaks when emphasising lines.
  - pymdownx.details # Collapsible admonition-style blocks containing further information.
  - pymdownx.escapeall # Backslashes escape everything.
  - pymdownx.caret # Superscripts and insert text.
  - pymdownx.superfences
  - pymdownx.tabbed # tabs
  - pymdownx.tilde # Strikethrough and underlines.
  - pymdownx.magiclink: # Better links and github references.
      provider: 'github'
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: 'noahniuwa'
      repo: 'fnx_docs'
 
